### ISSUE TITLE
add toot.lgbt

### ISSUE THREAD

**Issue by cmdr-nova** [NoraCodes/diffusion-output-list#17]
I'd like to 
- [x ] add
- [ ] remove
these domain(s) or URL(s) to the diffusion output list.

https://toot.lgbt

Criteria:

- [ x] This site includes diffusion output on a public-facing page.
- [ x] These images hypothetically replace human artworks. (That is, they are not
  examples of diffusion output for the purpose of technical discussion.)

If either criterion are not fulfilled, your domain(s) or URL(s) cannot be on the
list.

Please describe below why these criteria are or are not fulfilled.

I'm going to leave this up to you. This addition is a bit complicated, because it's an lgbt instance, but at the same time that elephant they're using as an instance banner is one of _the most_ obvious diffusion based photos I've ever seen.

**Comment by viscountexx** [comment]
I kept forgetting to look into this, but you're absolutely right. The signature on the art gives the game away especially lmao.

We already have queer-run sites including a blog on this list, and as the project description says - The list isn't strictly condemnation, just to provide warning. I see no issue with adding toot.lgbt to the list. Will write a PR today.
