### ISSUE TITLE
add mastodonbooks.net

### ISSUE THREAD

**Issue by cmdr-nova** [NoraCodes/diffusion-output-list#4]
I'd like to 
- [ x] add
- [ ] remove
these domain(s) or URL(s) to the diffusion output list.

https://mastodonbooks.net/about

Criteria:

- [x ] This site includes diffusion output on a public-facing page.
- [x ] These images hypothetically replace human artworks. (That is, they are not
  examples of diffusion output for the purpose of technical discussion.)

If either criterion are not fulfilled, your domain(s) or URL(s) cannot be on the
list.

Please describe below why these criteria are or are not fulfilled.

The mastodonbooks.net forward facing about page is using diffusion based imagery for its header, and its admin (Roger), is using the same thing for his public profile banner.

**Comment by NoraCodes** [comment]
Thank you!
